### ISSUE TITLE
Cobalt 9 priority

### ISSUE THREAD

**Issue by mekamak** [Serhioromano/cobalt-9#118]
cobalt 9 priority get stable version.
Rather than simplifying, training is a better option.
Knowing what works, the user will already learn.
I can prepare online training.
Thanks.

**Comment by kiranetph** [comment]
To get a stable version, feedback is needed since there are so many use cases that not everything can be covered while developing.
That is the purpose of Sergey's call to report problems, improvements and suggestions.

Simplyfing the usage of Cobalt will greatly improve the initial satisfaction of new users in using Cobalt, at the same improve the workflow for experience users.

A good example is the way Cobalt will handle parameters now by intelligently hiding non relevant or not needed parameters to get the users more focused on relevant parameters and getting not distracted or even intimidated by the myriad of features.

If Sergey can improve the usability for Cobalt, even less experienced users will benefit from the tools, therefore reducing the number of support calls.

I would suggest to wait a little with the production of online training materials (manuals/videos) for Cobalt 9, since I believe Sergey is actively working on some revolutionary improvements in ways how to bring the best out of Cobalt.

Any help for tutorials, manuals, videos etc is highly appreciated but should only follow when Cobalt9 reaches a more defined state, since as of now it is more on a Preview stage. 

Right now, testing, feedback and suggestions are the priority and we have a chance to actively participating and shaping the future of Cobalt.

**Comment by mekamak** [comment]
I used cobalt 7. I'm using cobalt 8. Cobalt 9 is also to be the stable version I did not understand what is missing .. ( The tank can not be light. ) Cobalt 9 needs the right introduction. Not simplification.
false priorities cause unnecessary delays and fatigue.
For Sergey.

**Comment by kiranetph** [comment]
> I used cobalt 7. I'm using cobalt 8. Cobalt 9 is also to be the stable version I did not understand what is missing .. 

Since you are using Cobalt for some time, you might remember that a discussion about Cobalt 9 goes way back to early 2013 with a possible release for it hinted at the 3rd quarter of 2013.
It was always visioned as a full front end system, following the evolution of the Emerald component.
As we all know, technologies, frameworks etc changing and some things became outdated. 
A good example might be the deprecation of MooTools.
In January 2016, a very early preview was published, but then the public development stopped at the same month. Now 3 1/2 years later, the public development continues. 
If you are saying that you don't understand what is "missing" over the last 6 1/2 years, then I presume you don't anticipate the fast development in the development of web components.
 
> ( The tank can not be light. ) Cobalt 9 needs the right introduction.

I don't fully understand what you want to express. If you think that Cobalt 9 will be a "light" version of Cobalt 8, then you are wrong. It is about evolution and compatibility to the upcoming Joomla 4 version. To the contrary, features will not be removed, they will still stay on and be improved for a better and easier use. 
Regarding the "right introduction": you are more than welcome to introduce it the "right" way. I would just wait until you will see a more mature version based on Sergey's plans. 

>  Not simplification.

I would rather support a system which will get easier to use than something which gets soooo complex that I will need the extensive training (as you stated above) to understand even the basics.

> false priorities cause unnecessary delays and fatigue.
> Sergey for.

No one is rushing anything and as stated earlier, the waiting time for Cobalt 9 is already more than 6 years, therefore I don't see any "unnecessary" delays here.   
Regarding the "false" priorities, I would suggest to read the **official comment** on the Mintjoomla site --> http://www.mintjoomla.com/blog/item/8466-update-cobalt-v-9-73-preview.html
"but significance of this feature in a fact that we have shifted our focus from gaining new complicated features, to simplicity, usability and look & feel. This is our main priority now. I rather make new Cobalt more beautiful and friendly than add another complex feature that will confuse users even more."

Hoping for your support and productive feedback.

**Comment by mekamak** [comment]
Cobalt is my favorite cck. I don't want Sergey to stop again. My goal is to contribute.Thanks.

**Comment by Serhioromano** [comment]
One of the most important points here that you miss is that simplification and usability are not only to help beginners. The main aim here is to extend Cobalt user base. Make Cobalt community bigger. And that is very important for survival. Right now it is a vital issue. If there will be no users to use Cobalt there will be no Cobalt.

@mekamak Your training material will play a very important role here. Where there is documentation on how to do things - there are things that are done. I very much appreciate your idea. But @kiranetph is right, we have to wait for a little until we have a stable version or at least RC.

> Cobalt 9 needs the right introduction. Not simplification. false priorities cause unnecessary delays and fatigue.

That is exactly right that "Cobalt 9 needs the right introduction". But remember my first statement, we need people or we gonna die. And people are scared of complications because most of the people are not self-confident Joomla experts. Most of them are beginners who look into the opportunity to create a small website for themselves. That is used to be why K2 is crazy popular. Because it was simple.

Our plan is to make Cobalt look & Feel simple like K2, but on-demand be the most flexible CCK out there.

So, if you try to focus on the simplicity of Cobalt while making training you can do more good for Cobalt and its future. And you will have a much bigger audience. 

Also when you create traning create it not for Joomla users. This way you will limit yourself to only Joomla community. Make it general training. For example, you make training on how to make Forum on your site. And then you tell them that you will use Joomla as a base and then Cobalt as forum. 

A lot of Cobalt users used to use Joomla just because there was Cobalt. They would leave Joomla long ago without it. So we can advertise cobalt to none Joomla users and make Cobalt the reason to start using Joomla.

@kiranetph  
>I don't fully understand what you want to express. 

He wants to say the opposite. He says that Cobalt is the tank. And tanks are made of thick metal and are heavy and you cannot avoid that fact. He tries to make a point that it is pointless to try to make tank light, but we rather have to accept complications of cobalt and its heaviness and do not take priority on senseless things. @mekamak sees priority to simplify Cobalt as not important.

**Comment by mekamak** [comment]
I am a fanatic user of joomla and cobalt. I agree cobalt is initially difficult. I had a hard time exploring. But the properties are worth it. I appreciate you trying to make it easier. In my opinion, the priority should be stable release. As a user, I would be happy to assist you. If there's anything I can do. Thanks.

**Comment by Serhioromano** [comment]
@mekamak 
> he priority should be stable release

This is by default. Of course, it is a priority. But this is not a priority for a vision for what Cobalt should be but a priority for time frame delivery. It is the main priority in that context.

I am looking forward to your training materials. I'll do everything to support you. I can post links on the site, even inside the extension in about page as getting started guide.
