### ISSUE TITLE
[9.81] - audit log - Error message

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#148]
Control Panel -> Audit Log

Warning: Invalid argument supplied for foreach() in /cobalt9/components/com_cobalt/layouts/search.php on line 15

**Comment by kiranetph** [comment]
same under Control Panel -> Notifications

**Comment by Serhioromano** [comment]
All these errors are gone after refactoring to BS4. The only problem it will take this week and another week to make a release. So not release this Friday, because I did not finish this feature and it is half baked.

A lot of things stopped working even non-Mootools.  On the other hand, I was able to fix a lot of tiny bugs, which might never come to the surface, but were there.
