### ISSUE TITLE
Properly update record on add new, attach existing - Field Relation

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#15]
Child field:
Update #_js_res_record when adding a new or attaching an existing record.

Otherwise we can never trust the "fields" column in #__js_res_record and its implementation would not make sense at all. 
Fixing this will also pave the way for removing unnecessary queries and speed improvements for full article view and article editing.

**Comment by Serhioromano** [comment]
regarding relational articles, we cannot rely on `records->fields`. It will always make queries to get a current list of relational content.  

This is due to a one-way relation. In the table, we only store relations from Child to Parent. Even when we save Parent we will still save relation in the Child. It inverts logic in Parent and Child. 

I know it might make more queries, (although not, to get a list of related records we will run query anyway) but this is the only way to make it stable.  Denormalization of DB is good, but not in this case. This is an exception. I am not sure I can make stable code to rely on `->fields`. If I did, I would make it at the beginning as all other fields. 

I am closing this for now, and when I'll be refactoring relation fields, I'll see how  I can improve.
