### ISSUE TITLE
Use uikit to solve js conflicts and bootstrap versions bugs

### ISSUE THREAD

**Issue by andiamine** [Serhioromano/cobalt-9#36]
I want discuss about uikit integration in cobalt cck, i have decided to use uikit in my joomla! extensions, cuz many clients have js conflicts with bootstrap versions, and css conflicts with template.
uikit will let you choose your custom prefix which avoid css conflicts  , also components of uikit use conflict-free naming conventions.

so i think if you use it in cobalt cck, all users problems related to css/js and tempalte will be decreased !

zoo cck already use uikit that's why is very stable and don't depend in templates or other js libraries.

**Comment by drinkmaker** [comment]
This is a great idea! I always use uikit in my projects. But in order to realize it will have a lot of rewrite. What do you think, Sergey?

**Comment by andiamine** [comment]
yes a lot of rewrite, but i think will solve all new problems related to templates that use bootstrap forever.

**Comment by andiamine** [comment]
i really hope this feature can be added !

**Comment by pepperstreet** [comment]
Hehe, I am Pro & Con at the same time. In the past, I have also mentioned the "yoo-strategy". Cooking his own soup is sometimes the saver way. No matter if it is 90% derivative, redundant work ;) 
For sure this would have benefits, but also disadvantages!

**Comment by andiamine** [comment]
@pepperstreet i think if uikit used cobalt will be more stable in frontend views , and i don't think there is a disadvantages.

**Comment by kiranetph** [comment]
Cobalt should not be dependent on a specific framework.
The main choice will be through the template someone will use for his project. 
Cobalt should have a ability to adjust to different frameworks without loading something additional.

**Comment by drinkmaker** [comment]
> Cobalt should not be dependent on a specific framework.

Yes, but he does. Now Cobalt is using bootstrap. What we have?
1. Helix framework https://drive.google.com/file/d/0Bxtm5PidFyMobFFzbkVVWV9Fbkk/
2. Warp framework https://drive.google.com/file/d/0Bxtm5PidFyMoMjJmdV9rbEVPLUE/
3. Gantry Framework https://drive.google.com/file/d/0Bxtm5PidFyMoY2g4cXNfMWFYc1U/
and so on...

I totally agree with that Cobalt should have a ability to adjust to different frameworks. It should work anywhere, anytime. Using UIkit with custom prefix will allow this is achieved. Yes, you have to download additional files. But hey:
![image](https://habrastorage.org/getpro/habr/post_images/10c/800/577/10c8005770f99ef21cb92582305b5319.jpg)

**Comment by drinkmaker** [comment]
UIKit allows use multiple UIKit and JQuery with NoConflict:

``` javascript
var myUIkit = UIkit.noConflict();
```

UIKit have own grid, use LESS, have style customizer.

**Comment by kiranetph** [comment]
The "cleanest" way to approach this problem would be cobalt templates, adjusting to the used front-end framework, dictated by the Joomla template.

Areas affected in Cobalt for changes would be:
1) Markup template
2) Article list template
3) Article full view template
4) Article submission template
5) Category template
6) Comment template
7) Control Panel template

If you have to modify them to work with UIkit (for example responsive grid system), why not make it work for some more at the same time? 
I'm sure there is a good way to solve this issue.
I''m playing around a little with the Control panel landing page and different grid systems.
Even though I'm not a programmer, the initial concept works quite well. 

Cobalt only provides basic templates. Most of the time you have to adjust them to your liking. Thats the time when you can choose what front-end to use.

**Comment by andiamine** [comment]
For programmers it's easy for them to implement any frontend framework by overriding views, but i'm talking about novice/beginner users, they think it's a bug or problem in cobalt, they will flood support forum and take much time from developer, and they are angry if the problem not solved, they can ask for refund or can add a bad review in JED ...  so the best solution is using a frontend framework that can work on all templates and i think the best choice for that is uikit , cuz u can choose custom prefix , lightweight and many more ...... so this will help @Serhioromano  to concentrate on php bugs and improvements.

**Comment by Serhioromano** [comment]
In the last update I introduces layout prefix global Cobalt parameter. What does that mean? You can create alternative templates for everything. For example you want to use uikit, then you set this parameter uikit. Now create any template (except cobalt manageable templates) file with prefix uikit. Eg: `views/cpanel/tmpl/uikit-default.php` and this file will be loaded instead of `default.php`.

This system allows us to create many different versions of layouts. uikit, BS3, ...

I think you can start doing that and create set of specific framework templates.

**Comment by andiamine** [comment]
oh good i didn't know this was done !

**Comment by pepperstreet** [comment]
Why is it necessary to enter a _prefix_? This looks unfamiliar compared to the usual Cobalt template parameters and J! core alternative layouts etc.  

Shouldn't it be a **simple select**, which lists the available files? 
I mean, I have to create my alternative file anyway. So why this extra input?  
For instance, I create a file with my name "defaultUIKIT.php" or "uikit.php", or "MyCpanel.php". 
This will be listed in the selectbox automatically. I would just select it. Done.  

---

BTW, it would be even more consistent, if it is a usual Cobalt template with (optional) parameters. 
For instance: Custom CSS field, headings, Icons and even custom classes etc.

**Comment by pepperstreet** [comment]
BTW, the cpanel default.php loads **navbar** from a Cobalt folder **layouts**. 
How is this going to be customized?  
Does it work like the J! core _layouts_ feature and overrides? If not, it should ;)

**Comment by kiranetph** [comment]
the prefix makes sense, since it is not only 1 template, but several "sub templates" for section, types, records etc etc 

But i would also like to get the usual select, since it would be nice to select some parameters ...
Example: display number of records, votes .... 

as of now, it seems the prefix approach does not support automatic inclusion of css/js files.

**Comment by pepperstreet** [comment]
**Should/can we move the last comments about this parameter to a current/open cpanel topic?** 
I still see no use case for the prefix? This is so different to the existing joomla and cobalt templates.
Regarding "Sub Templates". Which ones? The usual views are managed through the cobalt template manager... they do not benefit from this prefix setting?

**Comment by kiranetph** [comment]
@pepperstreet 
See the control panel as a set of templates. It starts with the panel itself, then you have all the "buttons" there like Section, Types, Records, Tags, Votes, Tools .... which have their own templates. Now if you have to provide access to every single"button" template, it might get unnecessary overloaded and messy. Therefore choosing a "prefix" with a fallback to the default template, if no prefix template is available in the respective "button" template folder, is a good start and makes sense to me. With this approach, you let cobalt handle the work for you --> cobalt will choose the right template for all the panel options based on the prefix.

Nevertheless i believe we should have access to the XML options of this panel prefix template.
Lets open another issue topic for discussion on this.

**Comment by pepperstreet** [comment]
Maybe I don't see the forest... ;) 
But all "sub-templates" would have to exist anyway...
to have a full conversion to another CSS framework.

**Comment by kiranetph** [comment]
They should exist for **best user experience**, yes ... but they are not a mandatory requirement. If they don't exist, there is a fallback to the "default" template.
Now to make it easy for the admin, just choose the "prefix" = master template in one place and cobalt will do the magic and select it automatically in all other places. 
The prefix parameter was the first step into this direction. I still believe and agree with you, that a select dropdown with the available templates would be a better user experience. They don't need to read a tooltip/help/manual to know what to type in. Only the experienced Cobalt admin/developer will know.
And then again, i would like to see the parameter button to change parameters for the panel template like icon, color, display of records etc. There might even "global parameters there" influencing the sub-templates.
All the work/configuration in C9 will now be front-end based --> Even more important that it will work smoothly with any template/front-end framework. 
Thats also the reason why I'm experimenting with 1 "universal" template (as described in the dashboard topic) to avoid a set of templates for every scenario. 
**One control panel template to rule them all**

**Comment by pepperstreet** [comment]
Probably this is THE best time to leave the Bootstrap v2 train all together?! No more need to follow the Joomla backend UI and CSS/JS framework.

Although, I have my doubts about finding the best "replacement". 
From the view of other templates and developers it might make sense to use BSv3. 
On the other hand, a framework has a big impact on Fields, Forms and JS stuff... 
I am mostly thinking about the more complex fields which have more UI and features: But should they always follow a bigger CSS framework? Often supplied default styles lead to more dependencies and in-compatibilities. 
I definitely see the time-saving aspects in development and the consistent form-UI appearance. But I would think twice before searching and implementing a project with specific "bootstrap style". i.e. uploads, calendars etc. I mean, wouldn't it be smarter to choose a clean, independent project without too strong relations to any framework?  
Alternatively, it might work IF the framework is really independent or "name-spaced". Hence the "yootheme"-strategy... Besides all their "vanity" and "obstinacy" in their product policy... ;) They seem to do very well with it: Choosing established projects... adding own improvements and some features... adding minimal and reduced styling. Bingo. No big issues, no big trouble. 
I have to admit that I was highly skeptical about UIKIT 1.0, but in the long run their strategy seems to work. };)

BTW @drinkmaker 
the size comparison chart is not correct and up-to-date, IMHO. 
You have to check out the latest and complete! size of all projects. (CSS/JS minified + fonts) 
Also to consider: A final website might load and add more than one framework! Simply due to other 3rd-party templates and extensions. Not to mention the J! core BS2.

**Comment by andiamine** [comment]
@Serhioromano i think it's better for default views (without prefix) to use by default uikit framework, for now default views use bs2.

also i can help to rewrite views if you add source code in repostory so i can fork it and pull.
