### ISSUE TITLE
replace bs2 by uikit in cobalt views

### ISSUE THREAD

**Issue by andiamine** [Serhioromano/cobalt-9#41]
@Serhioromano i think it's better for default views (without prefix) to use by default uikit framework instead of bs2.

i know it's a lot of work to change all views  .... but i will help if you agree. 

also i can help to rewrite views if you add source code in repository.

**Comment by kiranetph** [comment]
it would make the whole cobalt system dependent on 1 framework ...

**Comment by Serhioromano** [comment]
I do not think to move to UIKIT is a lot of work. It is quite compatible with BS. It all depends on strategy. @kiranetph do you think it is a smart move?

**Comment by andiamine** [comment]
@kiranetph  will not depend on 1 framework, prefix feature in views will be always available, i'm just talking about to change bs2 (which is outadated) to uikit, already explained that uikit will solve all css and js bugs with 3rd party extensions and templates

@Serhioromano yes i know , that's why i want help you to change views, i have many clients that use cobalt 8 , and the main problem is template compatibility, so if we move it to uikit we will concentrate on other things instead of wasting time in fixing clients bugs. , also i think we are not in rush, we want make something good and stable, cobalt 8 it's already stable, and can still work without any problem , so let's make cobalt 9 perfect.

**Comment by pepperstreet** [comment]
### Some thoughts...

More or less, Cobalt is already dependent of 1 framework. So actually no big difference, isn't it ;)
I fCobalt sticks with any BS version... more complex fields and their display and function might also dependent on a certain Bootstrap version. Even if own JS is added, the appearance and layout might depend on it to get a cross-browser style.

#### "The nature of the beast!":

If you want to get a good looking forms UI and layout in no time, plus modern JS components. Eventually you have to choose a "bigger" framework which provides these features. You have to depend on it, or create your own default styles and classes for weeks and months. 

How scary, I did not expect to write something like this about UIKIT :D 
I tend to agree with the benefits of compatibility and robustness in UIKIT. There are also some **useful additions** in _default grid classes_, _helper classes_, _grid classes on parent elements!_. Also like some extra features i.e. _FontAwesome_(also used for Radio/Checkbox!), _Off-Canvas_, _Dynamic Grid_(masonry fx & filter), _Nestable_, _Sortable_, _dropdown/pop-over_, _upload_, responsive Description-List (quite nice for Cobalt field labels ;) ) 

#### Some things I don't like:

The general yootheme upgrade policy with their products. Same applies to next UIKIT. v3 seems to be in the works, but as far as I have read there won't be an upgrade-path. It seems to be a new product. Maybe not so important if the current v2 is well-supported, feature-rich and rock-solid. But I think about the next WARP and template series: Apparently, WARP themes would have to load _two_ UIKIT versions!

#### Some things to consider with Cobalt:

How to get and integrate a complex fields like Calendar-field, advanced Uploads-field or Multi-Level-Select? And what kind of dependencies will they have with UIKIT? At least they might use classes for their appearance. Any useful JS that could be utilized? i.e. nestable and sortable for multi-value fields or layout editor etc. 

For sure, BSv3 is the most used framework among Joomla extensions/templates developers. Probably the biggest plus... although on 2nd sight: Often BS3 versions are slightly different or use only parts of the whole framework. I have also seen name-spaced versions etc. So I would not call it fool-prove if Cobalt relies on BSv3. Besides I have the same complains about upgrade-path to v4. (maybe overrated) 

#### Possible overhead... ahead!

UIKIT minified is about 150kB plus 80-100kB fonts (yep, on its own quite nice)
But we have to get the bigger picture:
- J! core or other extensions might also add BS2 or even Mootools! 
- In many cases, there will be a BSv3 powered template. At least additional extensions!
- WARP/uikit powered themes are solid, but not as widely spreaded as bootstrap powered ones. 
  So, it might be an advantage to choose BSv3, because there is a better chance to reduce overall loading size and time.

However, I slightly tend to UIKIT because of the extended features and possibilities mentioned earlier. The class names are somewhat longer, but the "readability" of the grid is better. I always had my problems with bootstrap3 in this regard :) 

UIKIT adds some CSS style to Radio/Checkboxes out-of-the-box! This is a real shortcoming in Bootstrap for years. Many 3rd-party addons available though, but mostly JS powered.
Bootstraps own iconfont is limited, but of smaller size. So there is still room to choose an additional custom font for icons.
UIKIT incorporates the famous FontAwesome. Quite comprehensive and all-purpose. But also more Kb. There are more default styles and possible combinations.

Bootstraps form inputs and their default appearance is more eye-pleasing and complete. 
Also like the _input-group-addon_ which allows to attach/append symbols, icons etc. 
Unfortunately UIKIT is more basic in this area, but easy customizable, too. 

##### Any conclusion? Looks like a classic "chicken and egg" situation. :) ;)

**Comment by kiranetph** [comment]
> @kiranetph do you think it is a smart move?

I am **not** in favour of choosing **any** framework for the core Cobalt templates at all.

For me Cobalt stands for unpreceded flexibility especially through the extensive template system.
If we look at a typical Joomla installation, everything is dictated by the Joomla template. Cobalt content should be able to adjust as close as possible to this template to avoid an awkward feeling. 

I would like to see Cobalt adjusting to every installation, therefore choosing a framework is just a shortcut solution for me, which will trigger only discussions about the "best" framework.... 

What do we need from those frameworks?
In the first place a responsive grid system. So we can either try to tell Cobalt through the main configuration what the existing setup is and then the templates will adjust accordingly, or provide a cobalt own solution (like a Flexbox approach).

**Don't limit yourself in choosing a specific framework, you experienced already the outcome of it....**

**Alternative** templates can always be customised towards a framework. 
There can be specific templates for UIkit or BS2/BS3/BS4 or whatever framework you want, but the **core templates** should not favour 1 specific framework and impose its usage to the customers. 

If someone is willing to produce **alternative** templates based on BS2/BS3/BS4 or UIkit or whatever else, it should be considered a valuable addition to the core Cobalt system and its development can be started immediately, regardless of what core Cobalt will use. Thats the beauty of the Cobalt template system ....

**Comment by pepperstreet** [comment]
@kiranetph Partly agree with you! A flexible and simple base is what I prefer personally and objectively. Unfortunately, it is not so easy to "split" Cobalt into frontend display, submission and configuration. 
Cobalt as a CCK and form-based frontend-submission system needs a lot of form elements. So my previous comment was influenced by watching from a sitebuilder/developer perspective. And how to "find" a supporting solution for all areas. Including real world usage in an average Joomla website (which consists of multiple extensions, and possibly a template/framework).
By choosing a framework, it might be interesting to look at the available JS components and extra features. Maybe something is useful for Cobalt? So one has not to re-invent the wheel.

There would be no issue and discussion at all, if everyone would build his own custom templates, or would simply follow the J! core techniques (old BS2). And if there were no template-clubs and marketplaces... But we all know, this is a dreamland ;)   

You are absolutely right, for frontend display it would not require a specific CSS framework. But what about submission forms and fields, user's homepage, settings etc.? 
_(PS: Everyone who ever tried to style and format a consistent form-UI knows what I am talking about. This is the second hell, after the browser-wars ;) )_

The J! core development seems unpredictable, IMHO. 
The current JUI/BS2 situation won't change in the short run... I know there are plans to allow more freedom in CSS/framework dependencies, but frankly speaking: I can't imagine this will happen in one of the next 3.x releases. Maybe in a later v3 which is supported until 2018 simultaneously. 
_(PS: Haha, two parallel Joomla core releases. We already know how this might end, right?)_

Joomla v4 seems to make a break in structure and underlying features. So it seems more realistic to expect a real change with the new, parallel branch.  

The long and the short of it, I would even tend to stay with JUI / BS2. At least for the configuration/parameters part and default submission. Then probably add alternative layouts to get the best compatibility. Responsive grid is quite easy to accomplish, but the formUI is another story. 

---

**BTW, the current BS2 Cobalt parameter tabs needs an update anyways**
#45 (separate issue/topic)

**Comment by andiamine** [comment]
Hi friends, the best choice is clear, framework that don't conflict with others and have many features , and i found uikit the best choice for that

## Benefits of cobalt + uikit
- Will work fine on any joomla frontend framework (gantry, warp, t3....)
- No js conflicts
- No css bugs
- Formvalidation support uikit too
- Will work fine inside any template that use bs2, bs3, bs4, foundation and uikit too.
- Developers @Serhioromano  will have less support for bugs related to client side
- Developers will have more time to solve issues related to server side
- uikit is lightweight, easy to customize, and extendabale
- uikit has many components than others : parallax, accordion, lightbox, timepicker, dynamic grid ... and more check here http://getuikit.com/docs/components.html
- uikit will let cobalt developers to make advanced and dynamic layouts (like using dynamic grid, flex layout...)
- and many more

## Now cobalt + bs2 (current release)
- Don't look good on joomla frontend framework (gantry, warp, t3....)
- Many js conflicts
- Many css bugs
- Don't work good in template that use bs3 , also i think will not work good in bs4
- many users report problems related to client side (css, js ..)
- Developers spend more time solving/checking issues related to template or conflict between bs2 and bs3
- and more ...

## Many frameworks loaded
- if your template use bs2 , so cobalt 8 will work good !! but if is bs3 , then u need to enable compatibility mode -> result you have 2 frameworks (bs2 + bs3) loaded and sometimes break other modules or content.

So it's better to be uikit + bs3

## For calendar and other 3rd party bs2 addons

There are many alternatives, exemple for calendar: 
here good calendar :
http://fullcalendar.io/
don't require bootsrap

**Comment by Serhioromano** [comment]
> @pepperstreet  The current JUI/BS2 situation won't change in the short run... I know there are plans to allow more freedom in CSS/framework dependencies, but frankly speaking: I can't imagine this will happen in one of the next 3.x releases. Maybe in a later v3 which is supported until 2018 simultaneously. 

Even if they bring it next update it is not something I am looking forward for. It will bring even more chaos.  What I want that Joomla properly keep BS updated to latest version with every new Joomla update. I was against the idea to create Joomla own CSS framework based on Bootstrap. But again, noone seems to listen to sound judgement in Joomla team.

**Comment by Serhioromano** [comment]
Joomla 4 will be shipped with BS4. I think that will solve the issue if new cobalt will support that BS version?

**Comment by mekamak** [comment]
Thanks Serhiromano.   i can't wait for cobalt 9 with joomla 4.
