### ISSUE TITLE
Frontend Dashboard Improvements

### ISSUE THREAD

**Issue by andiamine** [Serhioromano/cobalt-9#9]
i think it's a good idea to move everything in frontend, but many users will experience many js conflicts & css bugs if they use other templates that use bs3 or other customised templates , so i suggest to :
- add a floating small button "Co9 Dashboard" in left
- this floating button can be seen only by global moderator
- when user click on it will go to dashboard but with &tmpl=component in url i think this solution will solve css bugs and js conflicts also dashbaord will look good in full width. so it's good to force all urls of dashboard to be opened with tmpl=component param
- If non logged user access to dashbord should throw 403 error
- if logged user is not superadmin or global moderator try to access to dashboard should throw 403 error.

**Comment by kiranetph** [comment]
The &tmpl=component approach will strip off the normal navigation and the option to display other modules beside the component, which might be an additional help to the cpanel.

How about adding an option for a cpanel template in the configuration screen?
I want to configure things like page-header, especially icons, responsiveness etc ... 
There can be framework specific templates like gantry (using nucleus grid), T3 (bootstrap 3), Helix3, Warp, etc .... 
If a subtemplate (sections, types, etc) does not have a fitting tempate, it will fall back to default.
![cpanel](https://cloud.githubusercontent.com/assets/15226809/12237530/1a7d4190-b8ba-11e5-94f1-34393e535dc9.jpg)

**Comment by danielbidala** [comment]
I think we need only 2 options to choose from: BS2, BS3. If template doesn't use BS cobalt will load it (BS2 is joomla default). If template use BS2 than everything is OK. If template use BS3 we can select it from kiranetph's suggestion. So we need only 2 template.

**Comment by andiamine** [comment]
i think force dashboard to use component view only solve the problem of all templates conflicts , already check it in both bs2 and bs3 templates , works fine ! so no need to options

**Comment by kiranetph** [comment]
> @andiamine I believe there is a need for "options" or lets better say changeable parameter.  

For a template, i want to control the appearance as well as the content. Example --> the page title -- If i don't want to see "Cobalt Dashboard" but  "My application control center" instead, as of now i have to edit the default.php file, which will be overridden with the next update.. Or the icons etc etc ... At least there is a need for me to have the option to choose. 

One of Cobalt's weaknesses is the default visual presentation, therefore templates were introduced in the past so that everyone can adjust and customise it to their liking. 

For the dashboard/cpanel, it becomes a little more complex, since other templates are indirectly involved (sections, types, etc). Therefore an enhanced approach would be required. 
If i choose a different template than "default" in the configuration, the related templates should look first for a template with the same name in their respective template folder before using "default" as a safe fallback.

As mentioned in the chat, the "&tmpl=component" would limit it too much (at least in my opinion). If someone wants to use this, It can easily be accomplished now without any modifications to Cobalt 9 beta in using an "External URL" menu item and pasting "index.php?option=com_cobalt&view=cpanel&tmpl=component" into the link field.

**Comment by kiranetph** [comment]
@andiamine 

> If non logged user access to dashbord should throw 403 error
> if logged user is not superadmin or global moderator try to access to dashboard should throw 403 error.

Actually it should never throw an 403 error, This would be a bad practice and confuse users. A safe redirect would be much better. 
Or even configure a special access level for the "Global Moderator" and set this to the dashboard menu item. This will avoid unauthorised access and therefore errors.

**Comment by Serhioromano** [comment]
> @kiranetph  As mentioned in the chat, the "&tmpl=component" would limit it too much (at least in my opinion). If someone wants to use this, It can easily be accomplished now without any modifications to Cobalt 9 beta in using an "External URL" menu item and pasting `index.php?option=com_cobalt&view=cpanel&tmpl=component` into the link field.

It is not working actually this way. After any action it will return to standard view.

> @kiranetph How about adding an option for a cpanel template in the configuration screen?

What about template prefix parameter? For example default is `default.php` If you add `bs3` as prefix it will look for `bs3-default.php`? That is because form templates are usually `edit.php` by default. This prefix parameter might even work for non-admin views.

**Comment by kiranetph** [comment]
@Serhioromano 

> It is not working actually this way. After any action it will return to standard view.

Yes, right ... another reason not to go this way ...

> What about template prefix parameter?

That was exactly in my mind when i first commented above.. It would be a good and needed enhancement for the cpanel. thumbs up

**Comment by Serhioromano** [comment]
> What about template prefix parameter?

Done. 

> &tmpl=component

Done. Another parameter in config. By deafult it is off but it really may solve some issues for some people.
